# LnD Mapping : Exploratory Data Analysis of sales & marketing

Objectives
- Track outreach and follow-ups
- Analyze performance & progress
- Optimize maketing & sales strategy overtime

Data Source: Automate from Google spreadsheet

1. Dailytask Aqilah
2. Dailytask Nas
3. Master List
4. Client Listing Aqilah
5. Client Listing Nas

In [1]:
import pandas as pd

In [2]:
#only in jupyter
!pip install gspread

!pip install google-auth

#python prompt
#pip install gspread

#pip install google-auth

Requirement already satisfied: gspread in /opt/anaconda3/lib/python3.13/site-packages (6.2.1)
Requirement already satisfied: google-auth>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from gspread) (2.41.1)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /opt/anaconda3/lib/python3.13/site-packages (from gspread) (1.2.2)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth>=1.12.0->gspread) (5.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth>=1.12.0->gspread) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth>=1.12.0->gspread) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/anaconda3/lib/python3.13/site-packages (from rsa<5,>=3.1.4->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2025.6.15)
Requirement already satisfied: google-auth in /opt/anaconda3/lib/python3.13/site-packages (2.41.1)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth) (5.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/anaconda3/lib/python3.13/site-packages (from rsa<5,>=3.1.4->google-auth) (0.4.8)

## 1️⃣ Data Preparation

A. Dailytask

1. Read data
2. Merge data
   - Dailytask Aqilah
   - Dailytask Nas
3. Issue
   - Merging create new variable ie (Date, Date_x, Date_y)
   - Date format unable to read dd/mm/yy in powerBI (powerBI Date Format mm/dd/yy)

In [44]:
import gspread
from google.oauth2.service_account import Credentials

# Path to your downloaded service account key
SERVICE_ACCOUNT_FILE = 'lnd-mapping-8198f5560bee.json'
#for Power BI
# SERVICE_ACCOUNT_FILE = r'C:\Users\YourName\Documents\lnd-mapping-8198f5560bee.json'


# Define the scopes - adding more comprehensive scopes for gspread
SCOPES = [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive'  # Added drive scope which is often needed for gspread
]

# Authenticate and create a client
credentials = Credentials.from_service_account_file(
    SERVICE_ACCOUNT_FILE, scopes=SCOPES)

gc = gspread.authorize(credentials)

## Data Source: Dailytask

In [79]:
# Open the Google Sheet by name or URL

# Data source: Dailytask Aqilah
dtaqilah_sheet = gc.open_by_key('1VFZd6Ronogu1dqRFHbrElgYktX0hlclOQGRaxmrCYf0').sheet1

# Fetch all data
data_dtaqilah = dtaqilah_sheet.get_all_records()

In [80]:
# Convert Dailytask to pandas DataFrame
dtaqilah = pd.DataFrame(data_dtaqilah)

dtaqilah

,Day,Date,Industry,Company Contacted,PIC (Person in Charge),Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),Company Profile Sent (Yes/No),Outcome of Email,Follow-up Action Required,Next Follow-up Date,Remarks
0,Mon,18/08/2025,,,,,,,,,,,,
1,Tues,19/08/2025,,,,,,,,,,,,
2,Wed,20/08/2025,Hotels,SamaSama Hotel,Ms Previna,Call,Corporate trainings,,,,Replied,Program brochure and trainers profile sent,,
3,,20/08/2025,Hotels,SamaSama Hotel,Ms Previna,Email,Corporate trainings,,Yes,Yes,,Follow-up on 3/9/25,,1. Attention to Detail: Creating Memorable Gue...
4,,20/08/2025,Hotels,Corus KLCC,HR Team,Call,Corporate trainings,Not approchable,No,No,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,,08/10/2025,,Ho Wah Genting Berhad,HR Dept,Email,NLP trainings,,Yes,Yes,,,,
526,,08/10/2025,,Hospital Canselor Tuanku Muhriz UKM,PUAN SITI MASWANI,Email,NLP trainings,,Yes,Yes,,,,
527,,08/10/2025,,Hospital Islam Az-Zahrah,ENCIK HAFIZI,Email,NLP trainings,,Yes,Yes,,,,
528,,08/10/2025,,Hospital Pakar An-Nur,PUAN NUR ALYANI,Email,NLP trainings,,Yes,Yes,,,,
529,,08/10/2025,,Hospital Pakar Pusrawi Kuala Lumpur,TRAINING OFFICER,Email,NLP trainings,,Yes,Yes,,,,

In [47]:
# Data source: Dailytask Nas
dtnas_sheet = gc.open_by_key('13hC6OS4WJePzTlO9jX1b1BcO83nFi6ruEDwYKjegqp8').sheet1

# Fetch all data
data_dtnas = dtnas_sheet.get_all_records()

GSpreadException: the header row in the worksheet contains duplicates: ['']To manually set the header row, use the `expected_headers` parameter of `get_all_records()`

In [48]:
# Get raw data (list of lists)
data_dtnas_raw = dtnas_sheet.get_all_values()

# Convert to DataFrame manually
import pandas as pd
df_dtnas = pd.DataFrame(data_dtnas_raw)

# Optional: Set the first row as header (if you're okay with duplicate columns)
df_dtnas.columns = df_dtnas.iloc[0]  # first row becomes header
df_dtnas = df_dtnas[1:]  # remove header row from data

# Reset index
df_dtnas = df_dtnas.reset_index(drop=True)

# Preview
print(df_dtnas.head())

0        Date              Company Contacted PIC (Person in Charge)  \
0  19/08/2025   Sheraton Petaling Jaya Hotel         Mr Aiman Hafiz
1
2                       Qliq Damansara Hotel               Mr Aizam
3
4              Intercontinental Kuala Lumpur       Not approachable

0 Contact Method (Call/Email/WhatsApp/Visit) Training Program Promoted  \
0                           Call(19/08/2025)             food handling
1                          Email(19/08/2025)
2                           Call(19/08/2025)       hospitality program
3                          Email(19/08/2025)
4                           Not approachable          Not approachable

0   Outcome of Call Promotion Material Sent (Yes/No)  \
0     get pic email                              yes
1
2     get pic email                              yes
3
4  Not approachable                 Not approachable

0 Company Profile Sent (Yes/No)  Outcome of Email Follow-up Action Required  \
0                           yes       no response
1
2                           yes       no response
3
4              Not approachable  Not approachable          Not approachable

0  ...                   /
0  ...
1  ...
2  ...
3  ...
4  ...

[5 rows x 26 columns]

In [49]:
# Convert Client Listing to pandas DataFrame
df_dtnas = pd.DataFrame(df_dtnas)

df_dtnas

,Date,Company Contacted,PIC (Person in Charge),Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),Company Profile Sent (Yes/No),Outcome of Email,Follow-up Action Required,...,,,,,,,,,,/
0,19/08/2025,Sheraton Petaling Jaya Hotel,Mr Aiman Hafiz,Call(19/08/2025),food handling,get pic email,yes,yes,no response,,...,,,,,,,,,,
1,,,,Email(19/08/2025),,,,,,,...,,,,,,,,,,
2,,Qliq Damansara Hotel,Mr Aizam,Call(19/08/2025),hospitality program,get pic email,yes,yes,no response,,...,,,,,,,,,,
3,,,,Email(19/08/2025),,,,,,,...,,,,,,,,,,
4,,Intercontinental Kuala Lumpur,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,,TWL Holdings Berhad,Ms. Hoo,Email,NLP program,,yes,yes,,,...,,,,,,,,,,
398,,Tyden Engineering Sdn Bhd,HR,Email,NLP program,,yes,yes,,,...,,,,,,,,,,
399,,TZU CHI International School KL,HR,Email,NLP program,,yes,yes,,,...,,,,,,,,,,
400,,Trinerva Technology Sdn Bhd,MS AMY,Email,NLP program,,yes,yes,,,...,,,,,,,,,,
401,,Tropicana Corporation Berhad,Ms. Nursyaza,Email,NLP program,,yes,yes,,,...,,,,,,,,,,

In [50]:
print(df_dtnas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 26 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Date                                        402 non-null    object
 1   Company Contacted                           402 non-null    object
 2   PIC (Person in Charge)                      402 non-null    object
 3   Contact Method (Call/Email/WhatsApp/Visit)  402 non-null    object
 4   Training Program Promoted                   402 non-null    object
 5   Outcome of Call                             402 non-null    object
 6   Promotion Material Sent (Yes/No)            402 non-null    object
 7   Company Profile Sent (Yes/No)               402 non-null    object
 8   Outcome of Email                            402 non-null    object
 9   Follow-up Action Required                   402 non-null    object
 10  Next Follow-up Date                         402 non-null    object
 11  Remarks                                     402 non-null    object
 12                                              402 non-null    object
 13                                              402 non-null    object
 14                                              402 non-null    object
 15                                              402 non-null    object
 16                                              402 non-null    object
 17                                              402 non-null    object
 18                                              402 non-null    object
 19                                              402 non-null    object
 20                                              402 non-null    object
 21                                              402 non-null    object
 22                                              402 non-null    object
 23                                              402 non-null    object
 24                                              402 non-null    object
 25  /                                           402 non-null    object
dtypes: object(26)
memory usage: 81.8+ KB
None

In [51]:
# Drop Column
dtnas_drop = df_dtnas.drop(['','/'], axis = 1)
dtnas_drop

,Date,Company Contacted,PIC (Person in Charge),Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),Company Profile Sent (Yes/No),Outcome of Email,Follow-up Action Required,Next Follow-up Date,Remarks
0,19/08/2025,Sheraton Petaling Jaya Hotel,Mr Aiman Hafiz,Call(19/08/2025),food handling,get pic email,yes,yes,no response,,26/08/2025,
1,,,,Email(19/08/2025),,,,,,,,
2,,Qliq Damansara Hotel,Mr Aizam,Call(19/08/2025),hospitality program,get pic email,yes,yes,no response,,26/08/2025,
3,,,,Email(19/08/2025),,,,,,,,
4,,Intercontinental Kuala Lumpur,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable
...,...,...,...,...,...,...,...,...,...,...,...,...
397,,TWL Holdings Berhad,Ms. Hoo,Email,NLP program,,yes,yes,,,,
398,,Tyden Engineering Sdn Bhd,HR,Email,NLP program,,yes,yes,,,,
399,,TZU CHI International School KL,HR,Email,NLP program,,yes,yes,,,,
400,,Trinerva Technology Sdn Bhd,MS AMY,Email,NLP program,,yes,yes,,,,
401,,Tropicana Corporation Berhad,Ms. Nursyaza,Email,NLP program,,yes,yes,,,,

In [52]:
print(dtnas_drop.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Date                                        402 non-null    object
 1   Company Contacted                           402 non-null    object
 2   PIC (Person in Charge)                      402 non-null    object
 3   Contact Method (Call/Email/WhatsApp/Visit)  402 non-null    object
 4   Training Program Promoted                   402 non-null    object
 5   Outcome of Call                             402 non-null    object
 6   Promotion Material Sent (Yes/No)            402 non-null    object
 7   Company Profile Sent (Yes/No)               402 non-null    object
 8   Outcome of Email                            402 non-null    object
 9   Follow-up Action Required                   402 non-null    object
 10  Next Follow-up Date                         402 non-null    object
 11  Remarks                                     402 non-null    object
dtypes: object(12)
memory usage: 37.8+ KB
None

In [53]:
dtnas = dtnas_drop
dtnas

,Date,Company Contacted,PIC (Person in Charge),Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),Company Profile Sent (Yes/No),Outcome of Email,Follow-up Action Required,Next Follow-up Date,Remarks
0,19/08/2025,Sheraton Petaling Jaya Hotel,Mr Aiman Hafiz,Call(19/08/2025),food handling,get pic email,yes,yes,no response,,26/08/2025,
1,,,,Email(19/08/2025),,,,,,,,
2,,Qliq Damansara Hotel,Mr Aizam,Call(19/08/2025),hospitality program,get pic email,yes,yes,no response,,26/08/2025,
3,,,,Email(19/08/2025),,,,,,,,
4,,Intercontinental Kuala Lumpur,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable
...,...,...,...,...,...,...,...,...,...,...,...,...
397,,TWL Holdings Berhad,Ms. Hoo,Email,NLP program,,yes,yes,,,,
398,,Tyden Engineering Sdn Bhd,HR,Email,NLP program,,yes,yes,,,,
399,,TZU CHI International School KL,HR,Email,NLP program,,yes,yes,,,,
400,,Trinerva Technology Sdn Bhd,MS AMY,Email,NLP program,,yes,yes,,,,
401,,Tropicana Corporation Berhad,Ms. Nursyaza,Email,NLP program,,yes,yes,,,,

In [81]:
# MERGE data [dtnas,dtaqilah]
Dailytask_merge = pd.concat([dtnas, dtaqilah], axis = 0).reset_index(drop=True)

Dailytask_merge

,Date,Company Contacted,PIC (Person in Charge),Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),Company Profile Sent (Yes/No),Outcome of Email,Follow-up Action Required,Next Follow-up Date,Remarks,Day,Industry
0,19/08/2025,Sheraton Petaling Jaya Hotel,Mr Aiman Hafiz,Call(19/08/2025),food handling,get pic email,yes,yes,no response,,26/08/2025,,NaN,NaN
1,,,,Email(19/08/2025),,,,,,,,,NaN,NaN
2,,Qliq Damansara Hotel,Mr Aizam,Call(19/08/2025),hospitality program,get pic email,yes,yes,no response,,26/08/2025,,NaN,NaN
3,,,,Email(19/08/2025),,,,,,,,,NaN,NaN
4,,Intercontinental Kuala Lumpur,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,08/10/2025,Ho Wah Genting Berhad,HR Dept,Email,NLP trainings,,Yes,Yes,,,,,,
928,08/10/2025,Hospital Canselor Tuanku Muhriz UKM,PUAN SITI MASWANI,Email,NLP trainings,,Yes,Yes,,,,,,
929,08/10/2025,Hospital Islam Az-Zahrah,ENCIK HAFIZI,Email,NLP trainings,,Yes,Yes,,,,,,
930,08/10/2025,Hospital Pakar An-Nur,PUAN NUR ALYANI,Email,NLP trainings,,Yes,Yes,,,,,,
931,08/10/2025,Hospital Pakar Pusrawi Kuala Lumpur,TRAINING OFFICER,Email,NLP trainings,,Yes,Yes,,,,,,

In [82]:
# read data type
print(Dailytask_merge.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 932 entries, 0 to 931
Data columns (total 14 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Date                                        932 non-null    object
 1   Company Contacted                           932 non-null    object
 2   PIC (Person in Charge)                      932 non-null    object
 3   Contact Method (Call/Email/WhatsApp/Visit)  932 non-null    object
 4   Training Program Promoted                   932 non-null    object
 5   Outcome of Call                             932 non-null    object
 6   Promotion Material Sent (Yes/No)            932 non-null    object
 7   Company Profile Sent (Yes/No)               932 non-null    object
 8   Outcome of Email                            932 non-null    object
 9   Follow-up Action Required                   932 non-null    object
 10  Next Follow-up Date                         932 non-null    object
 11  Remarks                                     932 non-null    object
 12  Day                                         530 non-null    object
 13  Industry                                    530 non-null    object
dtypes: object(14)
memory usage: 102.1+ KB
None

In [84]:
# Change column name
Dtmerge_rename = Dailytask_merge.rename(columns={'Company Contacted': 'Company', 'PIC (Person in Charge)': 'PIC OF Training'})
Dtmerge_rename

,Date,Company,PIC OF Training,Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),Company Profile Sent (Yes/No),Outcome of Email,Follow-up Action Required,Next Follow-up Date,Remarks,Day,Industry
0,19/08/2025,Sheraton Petaling Jaya Hotel,Mr Aiman Hafiz,Call(19/08/2025),food handling,get pic email,yes,yes,no response,,26/08/2025,,NaN,NaN
1,,,,Email(19/08/2025),,,,,,,,,NaN,NaN
2,,Qliq Damansara Hotel,Mr Aizam,Call(19/08/2025),hospitality program,get pic email,yes,yes,no response,,26/08/2025,,NaN,NaN
3,,,,Email(19/08/2025),,,,,,,,,NaN,NaN
4,,Intercontinental Kuala Lumpur,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,08/10/2025,Ho Wah Genting Berhad,HR Dept,Email,NLP trainings,,Yes,Yes,,,,,,
928,08/10/2025,Hospital Canselor Tuanku Muhriz UKM,PUAN SITI MASWANI,Email,NLP trainings,,Yes,Yes,,,,,,
929,08/10/2025,Hospital Islam Az-Zahrah,ENCIK HAFIZI,Email,NLP trainings,,Yes,Yes,,,,,,
930,08/10/2025,Hospital Pakar An-Nur,PUAN NUR ALYANI,Email,NLP trainings,,Yes,Yes,,,,,,
931,08/10/2025,Hospital Pakar Pusrawi Kuala Lumpur,TRAINING OFFICER,Email,NLP trainings,,Yes,Yes,,,,,,

In [85]:
print(Dtmerge_rename['Date'].head())
# date in dd/mm/yy format

0    19/08/2025
1
2
3
4
Name: Date, dtype: object

In [58]:
print(Dtmerge_rename['Date'].head(10).tolist())

['19/08/2025', '', '', '', '', '', '20/08/2025', '', '', '']

In [86]:
# Step 1: Convert from string to datetime (using correct format)
Dtmerge_rename['Date'] = pd.to_datetime(Dtmerge_rename['Date'], format='%d/%m/%Y', errors='coerce')

# Step 2: Create a copy of the DataFrame (if needed)
Dtmerge_date = Dtmerge_rename.copy()

# Step 3: Format the 'Date' column into mm/dd/yy string format
Dtmerge_date['Date'] = Dtmerge_date['Date'].dt.strftime('%m/%d/%y')

# View the result
Dtmerge_date

,Date,Company,PIC OF Training,Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),Company Profile Sent (Yes/No),Outcome of Email,Follow-up Action Required,Next Follow-up Date,Remarks,Day,Industry
0,08/19/25,Sheraton Petaling Jaya Hotel,Mr Aiman Hafiz,Call(19/08/2025),food handling,get pic email,yes,yes,no response,,26/08/2025,,NaN,NaN
1,NaN,,,Email(19/08/2025),,,,,,,,,NaN,NaN
2,NaN,Qliq Damansara Hotel,Mr Aizam,Call(19/08/2025),hospitality program,get pic email,yes,yes,no response,,26/08/2025,,NaN,NaN
3,NaN,,,Email(19/08/2025),,,,,,,,,NaN,NaN
4,NaN,Intercontinental Kuala Lumpur,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,10/08/25,Ho Wah Genting Berhad,HR Dept,Email,NLP trainings,,Yes,Yes,,,,,,
928,10/08/25,Hospital Canselor Tuanku Muhriz UKM,PUAN SITI MASWANI,Email,NLP trainings,,Yes,Yes,,,,,,
929,10/08/25,Hospital Islam Az-Zahrah,ENCIK HAFIZI,Email,NLP trainings,,Yes,Yes,,,,,,
930,10/08/25,Hospital Pakar An-Nur,PUAN NUR ALYANI,Email,NLP trainings,,Yes,Yes,,,,,,
931,10/08/25,Hospital Pakar Pusrawi Kuala Lumpur,TRAINING OFFICER,Email,NLP trainings,,Yes,Yes,,,,,,

In [87]:
print(Dtmerge_date['Date'].head(10).tolist())

['08/19/25', nan, nan, nan, nan, nan, '08/20/25', nan, nan, nan]

In [88]:
Dtmerge_final = Dtmerge_date
Dtmerge_final

,Date,Company,PIC OF Training,Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),Company Profile Sent (Yes/No),Outcome of Email,Follow-up Action Required,Next Follow-up Date,Remarks,Day,Industry
0,08/19/25,Sheraton Petaling Jaya Hotel,Mr Aiman Hafiz,Call(19/08/2025),food handling,get pic email,yes,yes,no response,,26/08/2025,,NaN,NaN
1,NaN,,,Email(19/08/2025),,,,,,,,,NaN,NaN
2,NaN,Qliq Damansara Hotel,Mr Aizam,Call(19/08/2025),hospitality program,get pic email,yes,yes,no response,,26/08/2025,,NaN,NaN
3,NaN,,,Email(19/08/2025),,,,,,,,,NaN,NaN
4,NaN,Intercontinental Kuala Lumpur,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,Not approachable,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,10/08/25,Ho Wah Genting Berhad,HR Dept,Email,NLP trainings,,Yes,Yes,,,,,,
928,10/08/25,Hospital Canselor Tuanku Muhriz UKM,PUAN SITI MASWANI,Email,NLP trainings,,Yes,Yes,,,,,,
929,10/08/25,Hospital Islam Az-Zahrah,ENCIK HAFIZI,Email,NLP trainings,,Yes,Yes,,,,,,
930,10/08/25,Hospital Pakar An-Nur,PUAN NUR ALYANI,Email,NLP trainings,,Yes,Yes,,,,,,
931,10/08/25,Hospital Pakar Pusrawi Kuala Lumpur,TRAINING OFFICER,Email,NLP trainings,,Yes,Yes,,,,,,

In [111]:
print(Dtmerge_final['Training Program Promoted'].head().tolist())

['food handling', '', 'hospitality program', '', 'Not approachable']

In [113]:
Dtmerge_final['Training Program Promoted'].value_counts()

Training Program Promoted
NLP trainings            328
NLP program              231
Corporate trainings      200
                          86
manufacturing program     69
hospitality program       14
Not approachable           3
food handling              1
Name: count, dtype: int64

## Data source: Client Listing

In [66]:
# Data source: Client Listing
claqilah_sheet = gc.open_by_key('1LLWOFRSYBsRwE1jWxTzANgy8pQogE8LnhLoXcVay1v4').sheet1
#clnas_sheet = gc.open_by_key('1VFZd6Ronogu1dqRFHbrElgYktX0hlclOQGRaxmrCYf0').sheet1

# Fetch all data 
#data_claqilah = claqilah_sheet.get_all_records() #issue; duplicate header

# Fetch all data with expected_headers parameter to handle duplicate headers
# You can either provide your own headers or use the enumerate approach below
data_claqilah = claqilah_sheet.get_all_records(expected_headers=None)  # This will use column indices as key

In [67]:
# Get raw data (list of lists)
data_claqilah_raw = claqilah_sheet.get_all_values()

# Convert to DataFrame manually
import pandas as pd
df_claqilah = pd.DataFrame(data_claqilah_raw)

# Optional: Set the first row as header (if you're okay with duplicate columns)
df_claqilah.columns = df_claqilah.iloc[0]  # first row becomes header
df_claqilah = df_claqilah[1:]  # remove header row from data

# Reset index
df_claqilah = df_claqilah.reset_index(drop=True)

# Preview
print(df_claqilah.head())

0                               Company     Address  Phone Number  \
0                        W Kuala Lumpur  03-27868888       MR ASH
1            Aloft Kuala Lumpur Sentral  03-27231188    MS DAPHNE
2  AnCasa Hotel Kuala Lumpur, Chinatown  03-20266060      EN AMIR
3               ANSA Hotel Kuala Lumpur  03-21465000    MS MARYAM
4        Capri by Fraser, Bukit Bintang  03-23816888  MS EVENTHIA

0                       Email Address Training Needs           Stage  \
0                   hrwkl@whotels.com
1       daphne.anggas@alofthotels.com                  Proposal sent
2             ahklhr@ancasahotels.com                  Proposal sent
3  maryam.mohdabiden@berjayahotel.com                  Proposal sent
4          eventhia@capribyfraser.com                  Proposal sent

0 Est. value                                              Notes
0
1                                 daphne.anggas@alofthotels.com
2                    ahklhr@ancasahotels.com\ntraining calender
3             Called. \nRefered to Ms Joran\njoran.goi@ansah...
4             Emailed sent\n\nCalled. \nNing reservations.ku...

In [70]:
# Convert Client Listing to pandas DataFrame
claqilah = pd.DataFrame(df_claqilah)

claqilah

,Company,Address,Phone Number,Email Address,Training Needs,Stage,Est. value,Notes
0,W Kuala Lumpur,03-27868888,MR ASH,hrwkl@whotels.com,,,,
1,Aloft Kuala Lumpur Sentral,03-27231188,MS DAPHNE,daphne.anggas@alofthotels.com,,Proposal sent,,daphne.anggas@alofthotels.com
2,"AnCasa Hotel Kuala Lumpur, Chinatown",03-20266060,EN AMIR,ahklhr@ancasahotels.com,,Proposal sent,,ahklhr@ancasahotels.com\ntraining calender
3,ANSA Hotel Kuala Lumpur,03-21465000,MS MARYAM,maryam.mohdabiden@berjayahotel.com,,Proposal sent,,Called. \nRefered to Ms Joran\njoran.goi@ansah...
4,"Capri by Fraser, Bukit Bintang",03-23816888,MS EVENTHIA,eventhia@capribyfraser.com,,Proposal sent,,Emailed sent\n\nCalled. \nNing reservations.ku...
5,Corus KLCC,03-21618888,MS SITI NUR,hrd2@corushotel-kl.com,,,,Called. no answer. To make another calls.
6,Furama Bukit Bintang,03-27888888,MR WILLIAM,hrmgr.bukitbintang@furama.com,,,,Called. no answer. To make another calls.
7,Dorsett Kuala Lumpur,03-27161000,MR SUMREET,hr.kualalumpur@dorsetthotels.com,,,,Called. no answer. To make another calls.
8,ibis Kuala Lumpur City Centre,03-2778 3333,MS MIRA,hr@ibisklcc.com,,Proposal sent,,mira@ibisklcc.com
9,IDEAS KUALA LUMPUR,03-2614 8000,MR MUHAMMAD MAZNAN,hre@ideaskl.com,,Proposal sent,,Emailed Sent\nhrm@ideaskl.com Idayu
10,Impiana KLCC Hotel,03-2147 1111,MS NABILAH,hrcoordinator.iklcc@impiana.com,,Proposal sent,,Emailed sent\n\ncalled. \nRefered to HR manage...
11,INNSiDE by Meliá Kuala Lumpur Cheras,03-9133 0700,HR DEPT,human.resources@innsidekualalumpur.com,,Proposal sent,,jocerlyn.tan@melia.com
12,"Lanson Place Bukit Ceylon, Kuala Lumpur",03-2725 8888,MS PAULINE,pauline.yoong@lansonplace.com,,Proposal sent,,pauline.yoong@lansonplace.com
13,Mercure Kuala Lumpur Glenmarie,03-5030 2888,MS SHARIFAH,sharifah.iskandar@accor.com,returned,,,Called. no answer. To make another calls.
14,Novotel Kuala Lumpur City Centre,03-2147 0888,MS WHITNEY,H6324hr@accor.com,,,,Ms whitney
15,Oakwood Hotel & Residence Kuala Lumpur,03-2720 3888,HR MANAGER,dm.hotel-residence-kualalumpur@oakwood.com,returned,,,
16,Perdana Kuala Lumpur City Centre,03-7490 3333,PUAN ZARINA;PUAN HASMIDA,pklcc.humanresource@attanahotels.com,,,,Called. no answer. To make another calls.
17,Ramada Suites By Wyndham KLCC,03-2938 9888,MS PARVEENA,parveena.sundrasagal@ramadaklcc.com,,,,Ms Parveena
18,Santa Grand Signature Kuala Lumpur,03-2027 1969,MS SAHIRA,sahira.mahmudi@santagrandhotels.com.my,,,,Ms Shahia
19,STEG Kuala Lumpur,03-2603 6599,MS ELIS,people@stegkualalumpur.com,,,,Ms Elis
20,The Kuala Lumpur Journal Hotel,03-2110 2211,MS CHLOE GOH,hrm@kljournal.com,,,,Ms Jocerlyn Tan'
21,Vivatel Hotel Kuala Lumpur,03-9205 8888,EN KHAIRI,hrm@vivatel.com.my,,Proposal sent,,Emailed sent\n\nCalled.\nRefered to Ms. Asma e...
22,Bangi Resort Hotel,03-8210 2222,HR DEPT,hr@bangiresorthotel.com,,Proposal sent,,Emailed sent\n\nCalled. \nRefered to Pn Ida HR...
23,Cyberview Resort & Spa,03-8312 7000,MS NURUL,hrco@cyberviewresort.com,,,,sales@cyberviewresort
24,Eastin Hotel Kuala Lumpur,03-7665 1111,MS WAN MALISSA,hr.kl@eastin.com,,,,
25,Glenmarie Hotel & Golf Resort,03-7802 5200,MS SYAZWANA,hr@glenmarie.com.my,,,,
26,Tenera Hotel,03-8929 9600,MR FAIZUDIN,faizudin.ar@tenerahotel.com,,,,Farah \nmasturah.s@tenera.com.my
27,Mövenpick Hotel and Convention Centre KLIA,03-8661 8661,MR MOHAMAD ROZAI,mohamadrozai.zakaria@movenpick.com,,,,Mr Rozai
28,One World Hotel,03-7681 1111,MS HERNY,hr_training@oneworldhotel.com.my,,,,
29,"Sama-Sama Hotel, KLIA, Kuala Lumpur",03-8787 3333,MS PREVINA,previna.mohanen@samasamahotels.com,,Proposal sent,,Emailed sent\n\nCalled. \nRefered to Ms Previn...

In [63]:
# Data source: Clientlisting Nas
clnas_sheet = gc.open_by_key('1LqS_7yTssz1jVmVCDOKt5gRx1prNA7TxjkQ0fHBawF8').sheet1

# Fetch all data 
data_clnas = clnas_sheet.get_all_records() #issue; duplicate header

# Fetch all data with expected_headers parameter to handle duplicate headers
# You can either provide your own headers or use the enumerate approach below
data_clnas = clnas_sheet.get_all_records(expected_headers=None)  # This will use column indices as key

In [64]:
# Convert Clientlisting Nas to pandas DataFrame
clnas = pd.DataFrame(data_clnas)

clnas

,Company,Address,Phone Number,Email Address,Training Needs,Stage,Est. value,Notes,Collected Email,Date,notes,follow up
0,Qliq Damansara Hotel,03-86878421,MR AIZAM,contact@qliqdamansara.com,,Proposal sent,,Mr Aizam,finance@qliqdamansara.com,20/8/2025,done email on 21/8/2025,
1,InterContinental Kuala Lumpur by IHG,03-27826000,SALES AND MARKETING,intercontinental.kualalumpur@ihg.com,,Closed,,not answered,,20/8/2025,,
2,Concorde Hotel Kuala Lumpur,03-21442200,MA CAROLYN,training.chkl@concorde.net,,,,,,,,
3,Sheraton Petaling Jaya Hotel,03-76228888,MS WANI,mariaellena.hashim@sheraton.com,Food handling,Proposal sent,,MR Aiman Hafiz,aiman.jalani@sheraton.com,19/8/2025,done email on 21/8/2025,
4,Banyan Tree Kuala Lumpur,03-21131888,TRAINING & DEVELOPMENT DEPT,Learning-KL@banyantree.com,,,,,,,,
5,Traders Hotel Kuala Lumpur,03-23329888,MS ZETTY ZAINAL,hrdept.thkl@tradershotels.com,,Proposal sent,,,traders.thkl@tradershotel.com,19/8/2025,done email on 21/8/2025,
6,"Hotel Indigo Kuala Lumpur on the Park, an IHG ...",03-26303888,MR RAYNER SHANKAR,rayner.shankar@ihg.com,,,,,,,,
7,The Westin Kuala Lumpur,03-27318333,MS PREMALATHA,premalatha.siniah@westin.com,,,,,,,,
8,Hilton Kuala Lumpur,03-22642264,VINCENT,kulhi_hrd@hilton.com,,,,,vincent.chee@hilton.com,25/8/2025,done email on 25/8/2025,
9,DoubleTree by Hilton Kuala Lumpur,03-21727272,MR NASRUN,nasrun.sobri@hilton.com,,Closed,,not answered,,20/8/2025,,
10,THE FACE Suites,03-21681688,HR DEPT,hr.tfs@thefacehospitality.com,,,,,,,,
11,Hotel Maya Kuala Lumpur City Centre,03-27118866,HR DEPT,hre@hotelmaya.com.my,,Prospect,,not answered,,20/8/2025,,
12,Ascott Sentral Kuala Lumpur,03-27279999,MS ASHWINA,ashwina.jaganathan@the-ascott.com,,Prospect,,,,,done email on 25/8/2025,
13,Grand Hyatt Kuala Lumpur,03-21821234,HR MANAGER,kuagh.hr@hyatt.com,,,,,,,,
14,Else Kuala Lumpur,03-23003700,MR MARIAN,mariandavid@elseretreats.com,,,,,,,,
15,Royal Park Hotel @ UNITEN Bangi,03-89202064,MS SITI,siti.zulaikha@panpacific.com,,Prospect,,reach via whatsapp(Ms Shahira),1126635195,21/8/2025,done reach via ws on 21/8/2025,
16,Pullman Kuala Lumpur City Centre - Hotel & Res...,03-21708888,MS AGNES,hr@pullman-klcc.com,,,,,,,,
17,Four Seasons Hotel Kuala Lumpur,03-23828888,MR CHIAU FANG,chiaufang.chai@fourseasons.com,,Prospect,,,,,done email on 25/8/2025,
18,Imperial Lexis Kuala Lumpur,03-21771188,MR KESAVAN,hr@imperialexiskl.com,,,,,,,,
19,The St. Regis Kuala Lumpur,03-27271111,NORALIF,noralif.ahmad@stregis.com,,,,,,,,
20,Alila Bangsar Kuala Lumpur,03-22683888,HR DEPT,kulal-hr@hyatt.com,,Prospect,,reach back at 3 pm,,,,
21,Amari Kuala Lumpur,03-23305800,MS TARSYINIE,tarsyinie.sivakumar@amari.com,,,,,,,done email on 25/8/2025,
22,EQ Kuala Lumpur,03-27897777,MR REDZHWAN,redzhwan@kul.equatorial.com,,Prospect,,reach back on 25/8 after lunch. reach Ms Niko,,,,
23,"Hotel Stripes Kuala Lumpur, Autograph Collection",03-20380000,HR DEPT,support@ytlhotels-hrpservice.zendesk.com,,,,,,,,
24,Le Méridien Kuala Lumpur,03-22637888,MR GIRBAKRAN,girbakran.balachandran@lemeridien.com,,,,,,,,
25,M Resort & Hotel Kuala Lumpur,03-79326582,MS DAISY,daisy.ho@mresort-hotel.com.my,,,,,,,,
26,"Mandarin Oriental, Kuala Lumpur",03-23808888,MR WILLIAM,williaml@mohg.com,,,,,,,,
27,Renaissance Kuala Lumpur Hotel & Convention Ce...,03-27068088,MS INDY KAUR,indy.kaur@marriott.com,,,,,,,,
28,Seri Pacific Hotel Kuala Lumpur,03-40425555,EN NAZIM,hrteam@seripacific.com,,Prospect,,,nazim@seripacific.com,20/8/2025,done email on 21/8/2025,
29,Sofitel Kuala Lumpur Damansara,03-27206688,MR MERVIN,mervin.raymond@sofitel.com,,,,,,,done email on 25/8/2025,
30,"The Ritz-Carlton, Kuala Lumpur",03-21428000,MS EUNICE LIM,hr.spvr.rckl@ytlhotels.com,,,,,,,,
31,The RuMa Hotel and Residences,03-27780888,MS ADRIANAH,adrianah.abrahim@theruma.com,,Prospect,,,,21/8/2025,done email on 21/8/2025,

In [71]:
# MERGE data [dtnas,dtaqilah]
Clientlisting_merge = pd.concat([clnas, claqilah], axis = 0).reset_index(drop=True)

Clientlisting_merge

,Company,Address,Phone Number,Email Address,Training Needs,Stage,Est. value,Notes,Collected Email,Date,notes,follow up
0,Qliq Damansara Hotel,03-86878421,MR AIZAM,contact@qliqdamansara.com,,Proposal sent,,Mr Aizam,finance@qliqdamansara.com,20/8/2025,done email on 21/8/2025,
1,InterContinental Kuala Lumpur by IHG,03-27826000,SALES AND MARKETING,intercontinental.kualalumpur@ihg.com,,Closed,,not answered,,20/8/2025,,
2,Concorde Hotel Kuala Lumpur,03-21442200,MA CAROLYN,training.chkl@concorde.net,,,,,,,,
3,Sheraton Petaling Jaya Hotel,03-76228888,MS WANI,mariaellena.hashim@sheraton.com,Food handling,Proposal sent,,MR Aiman Hafiz,aiman.jalani@sheraton.com,19/8/2025,done email on 21/8/2025,
4,Banyan Tree Kuala Lumpur,03-21131888,TRAINING & DEVELOPMENT DEPT,Learning-KL@banyantree.com,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
57,Glenmarie Hotel & Golf Resort,03-7802 5200,MS SYAZWANA,hr@glenmarie.com.my,,,,,NaN,NaN,NaN,NaN
58,Tenera Hotel,03-8929 9600,MR FAIZUDIN,faizudin.ar@tenerahotel.com,,,,Farah \nmasturah.s@tenera.com.my,NaN,NaN,NaN,NaN
59,Mövenpick Hotel and Convention Centre KLIA,03-8661 8661,MR MOHAMAD ROZAI,mohamadrozai.zakaria@movenpick.com,,,,Mr Rozai,NaN,NaN,NaN,NaN
60,One World Hotel,03-7681 1111,MS HERNY,hr_training@oneworldhotel.com.my,,,,,NaN,NaN,NaN,NaN
61,"Sama-Sama Hotel, KLIA, Kuala Lumpur",03-8787 3333,MS PREVINA,previna.mohanen@samasamahotels.com,,Proposal sent,,Emailed sent\n\nCalled. \nRefered to Ms Previn...,NaN,NaN,NaN,NaN

In [74]:
Clmerge_rename = Clientlisting_merge.rename(columns={'Address ': 'Phone Number', 'Phone Number': 'PIC OF Training'})
Clmerge_rename

,Company,Phone Number,PIC OF Training,Email Address,Training Needs,Stage,Est. value,Notes,Collected Email,Date,notes,follow up
0,Qliq Damansara Hotel,03-86878421,MR AIZAM,contact@qliqdamansara.com,,Proposal sent,,Mr Aizam,finance@qliqdamansara.com,20/8/2025,done email on 21/8/2025,
1,InterContinental Kuala Lumpur by IHG,03-27826000,SALES AND MARKETING,intercontinental.kualalumpur@ihg.com,,Closed,,not answered,,20/8/2025,,
2,Concorde Hotel Kuala Lumpur,03-21442200,MA CAROLYN,training.chkl@concorde.net,,,,,,,,
3,Sheraton Petaling Jaya Hotel,03-76228888,MS WANI,mariaellena.hashim@sheraton.com,Food handling,Proposal sent,,MR Aiman Hafiz,aiman.jalani@sheraton.com,19/8/2025,done email on 21/8/2025,
4,Banyan Tree Kuala Lumpur,03-21131888,TRAINING & DEVELOPMENT DEPT,Learning-KL@banyantree.com,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
57,Glenmarie Hotel & Golf Resort,03-7802 5200,MS SYAZWANA,hr@glenmarie.com.my,,,,,NaN,NaN,NaN,NaN
58,Tenera Hotel,03-8929 9600,MR FAIZUDIN,faizudin.ar@tenerahotel.com,,,,Farah \nmasturah.s@tenera.com.my,NaN,NaN,NaN,NaN
59,Mövenpick Hotel and Convention Centre KLIA,03-8661 8661,MR MOHAMAD ROZAI,mohamadrozai.zakaria@movenpick.com,,,,Mr Rozai,NaN,NaN,NaN,NaN
60,One World Hotel,03-7681 1111,MS HERNY,hr_training@oneworldhotel.com.my,,,,,NaN,NaN,NaN,NaN
61,"Sama-Sama Hotel, KLIA, Kuala Lumpur",03-8787 3333,MS PREVINA,previna.mohanen@samasamahotels.com,,Proposal sent,,Emailed sent\n\nCalled. \nRefered to Ms Previn...,NaN,NaN,NaN,NaN

In [75]:
# Step 1: Convert from string to datetime (using correct format)
Clmerge_rename['Date'] = pd.to_datetime(Clmerge_rename['Date'], format='%d/%m/%Y', errors='coerce')

# Step 2: Create a copy of the DataFrame (if needed)
Clmerge_date = Clmerge_rename.copy()

# Step 3: Format the 'Date' column into mm/dd/yy string format
Clmerge_date['Date'] = Clmerge_date['Date'].dt.strftime('%m/%d/%y')

# View the result
Clmerge_date

,Company,Phone Number,PIC OF Training,Email Address,Training Needs,Stage,Est. value,Notes,Collected Email,Date,notes,follow up
0,Qliq Damansara Hotel,03-86878421,MR AIZAM,contact@qliqdamansara.com,,Proposal sent,,Mr Aizam,finance@qliqdamansara.com,08/20/25,done email on 21/8/2025,
1,InterContinental Kuala Lumpur by IHG,03-27826000,SALES AND MARKETING,intercontinental.kualalumpur@ihg.com,,Closed,,not answered,,08/20/25,,
2,Concorde Hotel Kuala Lumpur,03-21442200,MA CAROLYN,training.chkl@concorde.net,,,,,,NaN,,
3,Sheraton Petaling Jaya Hotel,03-76228888,MS WANI,mariaellena.hashim@sheraton.com,Food handling,Proposal sent,,MR Aiman Hafiz,aiman.jalani@sheraton.com,08/19/25,done email on 21/8/2025,
4,Banyan Tree Kuala Lumpur,03-21131888,TRAINING & DEVELOPMENT DEPT,Learning-KL@banyantree.com,,,,,,NaN,,
...,...,...,...,...,...,...,...,...,...,...,...,...
57,Glenmarie Hotel & Golf Resort,03-7802 5200,MS SYAZWANA,hr@glenmarie.com.my,,,,,NaN,NaN,NaN,NaN
58,Tenera Hotel,03-8929 9600,MR FAIZUDIN,faizudin.ar@tenerahotel.com,,,,Farah \nmasturah.s@tenera.com.my,NaN,NaN,NaN,NaN
59,Mövenpick Hotel and Convention Centre KLIA,03-8661 8661,MR MOHAMAD ROZAI,mohamadrozai.zakaria@movenpick.com,,,,Mr Rozai,NaN,NaN,NaN,NaN
60,One World Hotel,03-7681 1111,MS HERNY,hr_training@oneworldhotel.com.my,,,,,NaN,NaN,NaN,NaN
61,"Sama-Sama Hotel, KLIA, Kuala Lumpur",03-8787 3333,MS PREVINA,previna.mohanen@samasamahotels.com,,Proposal sent,,Emailed sent\n\nCalled. \nRefered to Ms Previn...,NaN,NaN,NaN,NaN

In [76]:
Clmerge_final = Clmerge_date
Clmerge_final

,Company,Phone Number,PIC OF Training,Email Address,Training Needs,Stage,Est. value,Notes,Collected Email,Date,notes,follow up
0,Qliq Damansara Hotel,03-86878421,MR AIZAM,contact@qliqdamansara.com,,Proposal sent,,Mr Aizam,finance@qliqdamansara.com,08/20/25,done email on 21/8/2025,
1,InterContinental Kuala Lumpur by IHG,03-27826000,SALES AND MARKETING,intercontinental.kualalumpur@ihg.com,,Closed,,not answered,,08/20/25,,
2,Concorde Hotel Kuala Lumpur,03-21442200,MA CAROLYN,training.chkl@concorde.net,,,,,,NaN,,
3,Sheraton Petaling Jaya Hotel,03-76228888,MS WANI,mariaellena.hashim@sheraton.com,Food handling,Proposal sent,,MR Aiman Hafiz,aiman.jalani@sheraton.com,08/19/25,done email on 21/8/2025,
4,Banyan Tree Kuala Lumpur,03-21131888,TRAINING & DEVELOPMENT DEPT,Learning-KL@banyantree.com,,,,,,NaN,,
...,...,...,...,...,...,...,...,...,...,...,...,...
57,Glenmarie Hotel & Golf Resort,03-7802 5200,MS SYAZWANA,hr@glenmarie.com.my,,,,,NaN,NaN,NaN,NaN
58,Tenera Hotel,03-8929 9600,MR FAIZUDIN,faizudin.ar@tenerahotel.com,,,,Farah \nmasturah.s@tenera.com.my,NaN,NaN,NaN,NaN
59,Mövenpick Hotel and Convention Centre KLIA,03-8661 8661,MR MOHAMAD ROZAI,mohamadrozai.zakaria@movenpick.com,,,,Mr Rozai,NaN,NaN,NaN,NaN
60,One World Hotel,03-7681 1111,MS HERNY,hr_training@oneworldhotel.com.my,,,,,NaN,NaN,NaN,NaN
61,"Sama-Sama Hotel, KLIA, Kuala Lumpur",03-8787 3333,MS PREVINA,previna.mohanen@samasamahotels.com,,Proposal sent,,Emailed sent\n\nCalled. \nRefered to Ms Previn...,NaN,NaN,NaN,NaN

## Data Source: Masterlist

In [9]:
# Open the Google Sheet by name or URL

# Data source: Dailytask Aqilah
masterlist_sheet = gc.open_by_key('1KUHaaK4IQO8HJb2pgjhxN9dYD2593_HuUVJeZaV-G-w').sheet1

# Fetch all data
data_masterlist = masterlist_sheet.get_all_records()

# Print the data
#for row in data_dtaqilah:
    #print(row)

GSpreadException: the header row in the worksheet contains duplicates: ['']To manually set the header row, use the `expected_headers` parameter of `get_all_records()`

In [10]:
# Get raw data (list of lists)
data_masterlist_raw = masterlist_sheet.get_all_values()

# Convert to DataFrame manually
import pandas as pd
df_masterlist = pd.DataFrame(data_masterlist_raw)

# Optional: Set the first row as header (if you're okay with duplicate columns)
df_masterlist.columns = df_masterlist.iloc[0]  # first row becomes header
df_masterlist = df_masterlist[1:]  # remove header row from data

# Reset index
df_masterlist = df_masterlist.reset_index(drop=True)

# Preview
print(df_masterlist.head())

0                           Company                              Industry   \
0                1 Secretary Sdn Bhd                     Business Services
1  7-Eleven Malaysia Holdings Berhad           Retail (Convenience Stores)
2                          A.S.S.A.R         Investment / Asset Management
3             ABB Malaysia Sdn. Bhd.   Industrial Automation & Engineering
4       ABF Malaysia Bond Index Fund  Financial Services (Investment Fund)

0         TelNo PIC OF Training                    Email
0  011-33800061              HR       hello@1company.com
1   03-21191711     Ms. Farhana  training@7eleven.com.my
2    082-231085         MR AZIM         hrd@assar.com.my
3   03-56284888         HR DEPT      askhr.my@my.abb.com
4   03-21673000             HOD     hrld@ambankgroup.com

In [11]:
# Convert Client Listing to pandas DataFrame
df_masterlist = pd.DataFrame(df_masterlist)

df_masterlist

,Company,Industry,TelNo,PIC OF Training,Email,,
0,1 Secretary Sdn Bhd,Business Services,011-33800061,HR,hello@1company.com,,
1,7-Eleven Malaysia Holdings Berhad,Retail (Convenience Stores),03-21191711,Ms. Farhana,training@7eleven.com.my,,
2,A.S.S.A.R,Investment / Asset Management,082-231085,MR AZIM,hrd@assar.com.my,,
3,ABB Malaysia Sdn. Bhd.,Industrial Automation & Engineering,03-56284888,HR DEPT,askhr.my@my.abb.com,,
4,ABF Malaysia Bond Index Fund,Financial Services (Investment Fund),03-21673000,HOD,hrld@ambankgroup.com,,
...,...,...,...,...,...,...,...
1332,Yuen Chun Industries Sdn Bhd,Manufacturer,06-79712233,Ms. Azira,noor.azira@yuenchun.com,,
1333,Zanko Sdn Bhd,Software company,03-91730045,Admin,admin@zanko.com.my,,
1334,Zen Tech International Berhad,,03-22023330,Ms. Stacy,zentech980115@gmail.com,,
1335,Zenith Hotel Putrajaya,Hotel,03-8893 9993,MR AMIRUL,hrexec@zenithputrajaya.com,,
1336,Zhenta Steel,Factory equipment supplier,03-32903088,MR TEOH,zhentasteelacc@gmail.com,,

In [12]:
print(df_masterlist.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          1337 non-null   object
 1   Industry         1337 non-null   object
 2   TelNo            1337 non-null   object
 3   PIC OF Training  1337 non-null   object
 4   Email            1337 non-null   object
 5                    1337 non-null   object
 6                    1337 non-null   object
dtypes: object(7)
memory usage: 73.2+ KB
None

In [14]:
# Drop Column
masterlist_drop = df_masterlist.drop(['',''], axis = 1)
masterlist_drop

,Company,Industry,TelNo,PIC OF Training,Email
0,1 Secretary Sdn Bhd,Business Services,011-33800061,HR,hello@1company.com
1,7-Eleven Malaysia Holdings Berhad,Retail (Convenience Stores),03-21191711,Ms. Farhana,training@7eleven.com.my
2,A.S.S.A.R,Investment / Asset Management,082-231085,MR AZIM,hrd@assar.com.my
3,ABB Malaysia Sdn. Bhd.,Industrial Automation & Engineering,03-56284888,HR DEPT,askhr.my@my.abb.com
4,ABF Malaysia Bond Index Fund,Financial Services (Investment Fund),03-21673000,HOD,hrld@ambankgroup.com
...,...,...,...,...,...
1332,Yuen Chun Industries Sdn Bhd,Manufacturer,06-79712233,Ms. Azira,noor.azira@yuenchun.com
1333,Zanko Sdn Bhd,Software company,03-91730045,Admin,admin@zanko.com.my
1334,Zen Tech International Berhad,,03-22023330,Ms. Stacy,zentech980115@gmail.com
1335,Zenith Hotel Putrajaya,Hotel,03-8893 9993,MR AMIRUL,hrexec@zenithputrajaya.com
1336,Zhenta Steel,Factory equipment supplier,03-32903088,MR TEOH,zhentasteelacc@gmail.com

In [15]:
print(masterlist_drop.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          1337 non-null   object
 1   Industry         1337 non-null   object
 2   TelNo            1337 non-null   object
 3   PIC OF Training  1337 non-null   object
 4   Email            1337 non-null   object
dtypes: object(5)
memory usage: 52.4+ KB
None

In [102]:
# Rename column
masterlist_rename = masterlist_drop.rename(columns={'Company ': 'Company', 'Industry ': 'Industry'})
masterlist_rename

,Company,Industry,TelNo,PIC OF Training,Email
0,1 Secretary Sdn Bhd,Business Services,011-33800061,HR,hello@1company.com
1,7-Eleven Malaysia Holdings Berhad,Retail (Convenience Stores),03-21191711,Ms. Farhana,training@7eleven.com.my
2,A.S.S.A.R,Investment / Asset Management,082-231085,MR AZIM,hrd@assar.com.my
3,ABB Malaysia Sdn. Bhd.,Industrial Automation & Engineering,03-56284888,HR DEPT,askhr.my@my.abb.com
4,ABF Malaysia Bond Index Fund,Financial Services (Investment Fund),03-21673000,HOD,hrld@ambankgroup.com
...,...,...,...,...,...
1332,Yuen Chun Industries Sdn Bhd,Manufacturer,06-79712233,Ms. Azira,noor.azira@yuenchun.com
1333,Zanko Sdn Bhd,Software company,03-91730045,Admin,admin@zanko.com.my
1334,Zen Tech International Berhad,,03-22023330,Ms. Stacy,zentech980115@gmail.com
1335,Zenith Hotel Putrajaya,Hotel,03-8893 9993,MR AMIRUL,hrexec@zenithputrajaya.com
1336,Zhenta Steel,Factory equipment supplier,03-32903088,MR TEOH,zhentasteelacc@gmail.com

In [103]:
Masterlist_final = masterlist_rename
Masterlist_final

,Company,Industry,TelNo,PIC OF Training,Email
0,1 Secretary Sdn Bhd,Business Services,011-33800061,HR,hello@1company.com
1,7-Eleven Malaysia Holdings Berhad,Retail (Convenience Stores),03-21191711,Ms. Farhana,training@7eleven.com.my
2,A.S.S.A.R,Investment / Asset Management,082-231085,MR AZIM,hrd@assar.com.my
3,ABB Malaysia Sdn. Bhd.,Industrial Automation & Engineering,03-56284888,HR DEPT,askhr.my@my.abb.com
4,ABF Malaysia Bond Index Fund,Financial Services (Investment Fund),03-21673000,HOD,hrld@ambankgroup.com
...,...,...,...,...,...
1332,Yuen Chun Industries Sdn Bhd,Manufacturer,06-79712233,Ms. Azira,noor.azira@yuenchun.com
1333,Zanko Sdn Bhd,Software company,03-91730045,Admin,admin@zanko.com.my
1334,Zen Tech International Berhad,,03-22023330,Ms. Stacy,zentech980115@gmail.com
1335,Zenith Hotel Putrajaya,Hotel,03-8893 9993,MR AMIRUL,hrexec@zenithputrajaya.com
1336,Zhenta Steel,Factory equipment supplier,03-32903088,MR TEOH,zhentasteelacc@gmail.com

## Mere All data 
- Masterlist_final
- Dtmerge_final
- Clmerge_final

In [104]:
# Merge all data
Mergealldata = pd.concat([Masterlist_final, Dtmerge_final, Clmerge_final], axis = 0).reset_index(drop=True)

Mergealldata

,Company,Industry,TelNo,PIC OF Training,Email,Date,Contact Method (Call/Email/WhatsApp/Visit),Training Program Promoted,Outcome of Call,Promotion Material Sent (Yes/No),...,Day,Phone Number,Email Address,Training Needs,Stage,Est. value,Notes,Collected Email,notes,follow up
0,1 Secretary Sdn Bhd,Business Services,011-33800061,HR,hello@1company.com,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7-Eleven Malaysia Holdings Berhad,Retail (Convenience Stores),03-21191711,Ms. Farhana,training@7eleven.com.my,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A.S.S.A.R,Investment / Asset Management,082-231085,MR AZIM,hrd@assar.com.my,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABB Malaysia Sdn. Bhd.,Industrial Automation & Engineering,03-56284888,HR DEPT,askhr.my@my.abb.com,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABF Malaysia Bond Index Fund,Financial Services (Investment Fund),03-21673000,HOD,hrld@ambankgroup.com,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,Glenmarie Hotel & Golf Resort,NaN,NaN,MS SYAZWANA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,03-7802 5200,hr@glenmarie.com.my,,,,,NaN,NaN,NaN
2327,Tenera Hotel,NaN,NaN,MR FAIZUDIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,03-8929 9600,faizudin.ar@tenerahotel.com,,,,Farah \nmasturah.s@tenera.com.my,NaN,NaN,NaN
2328,Mövenpick Hotel and Convention Centre KLIA,NaN,NaN,MR MOHAMAD ROZAI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,03-8661 8661,mohamadrozai.zakaria@movenpick.com,,,,Mr Rozai,NaN,NaN,NaN
2329,One World Hotel,NaN,NaN,MS HERNY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,03-7681 1111,hr_training@oneworldhotel.com.my,,,,,NaN,NaN,NaN
2330,"Sama-Sama Hotel, KLIA, Kuala Lumpur",NaN,NaN,MS PREVINA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,03-8787 3333,previna.mohanen@samasamahotels.com,,Proposal sent,,Emailed sent\n\nCalled. \nRefered to Ms Previn...,NaN,NaN,NaN

In [105]:
print(Mergealldata.columns.tolist())

['Company', 'Industry', 'TelNo', 'PIC OF Training', 'Email', 'Date', 'Contact Method (Call/Email/WhatsApp/Visit)', 'Training Program Promoted', 'Outcome of Call', 'Promotion Material Sent (Yes/No)', 'Company Profile Sent (Yes/No)', 'Outcome of Email', 'Follow-up Action Required', 'Next Follow-up Date', 'Remarks', 'Day', 'Phone Number', 'Email Address', 'Training Needs ', 'Stage', 'Est. value', 'Notes', 'Collected Email', 'notes', 'follow up']

In [106]:
print(Mergealldata['Training Program Promoted'].head(10).tolist())

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [114]:
Mergealldata['Training Program Promoted'].value_counts()

Training Program Promoted
NLP trainings            328
NLP program              231
Corporate trainings      200
                          86
manufacturing program     69
hospitality program       14
Not approachable           3
food handling              1
Name: count, dtype: int64

In [115]:
Mergealldata['Contact Method (Call/Email/WhatsApp/Visit)'].value_counts()

Contact Method (Call/Email/WhatsApp/Visit)
Email                651
Call                  91
call                  65
email                 65
Call                  28
                      18
Not approachable       3
Email(19/08/2025)      2
Call(19/08/2025)       2
Whatsapp               2
whatsapp               2
WhatsApp               2
call                   1
Name: count, dtype: int64

## EDA
data highlight for EDA
- Company
- Industry
- Contact Method
- Training Program Promoted
- Stage
- Est. value

## 🔁 Set Up Auto-Refresh (Scheduled Refresh)

Now that your report is published:

- Go to Power BI Service
- Open the workspace where you published the report
- Click the three dots ... next to the dataset > Settings
- Under Data source credentials, make sure:
- Authentication is set (if needed)
- Privacy level is set to "Public" or appropriate level
- Scroll down to Scheduled refresh
- Turn on
- Set your preferred refresh frequency (e.g., daily/hourly)